---
title: "steps-by-step"
format:
  html:
    embed-resources: true
editor: visual
---

# demop

-   Create `demop` using Rstudio (alt usethis::create_package)
-   Look at DESCRIPTION
-   Add first function `copy ..\demo\excel.R R`
    -   `usethis::use_package("readxl")` and `usethis::use_package("dplyr")`
    -   Turn into function, improve with "..."
    -   Add namespace to function calls (readxl:: dplyr::)
    -   Remove (or rename NAMESPACE)
    -   Add roxygen documentation and run `devtools::document` ( \#'\\dontrun{} )
    -   look at `NAMESPACE` and folder `man`
-   Add package data
    -   `copy ..\demo\growth.R R`
    -   `usethis::use_roxygen_md()` (to get some optional roxygen functionality)
    -   create data-raw `copy ..\demo\ArterData.csv data-raw` and `copy ..\demo\DATA.R data-raw`
    -   open `DATA.R` and run it (creates folder `data` and `species_data.rda`
    -   run `devtools::document()` (complains about data doc)
    -   copy prepared docs `copy ..\demo\DATA_documentation.R R`
    -   run `devtools::document()` (again)
    -   Done! We now have a package with a couple of functions, a built in dataset and documentation for both.
-   Add other files we want installed
    - Create folder "inst" `usethis::use_directory("inst")`
    - Copy files to be installed `copy ..\demo\*.xlsx inst\extdata`
    - Reload and demo
    - `myfiles <- system.file("extdata", package = "demop")`
    - `slurp_excel(fnames = myfiles)`
-   Install and share
    -   In Rstudio tab `Build` click `Install`
    -   Share zip-file
        -   In Rstudio tab `Build` `More` -\> `Build Source Package`
        -   `install.packages(pkgs = "demop_0.1.0.zip")`
    -   If on Github
        -   `remotes::install_github("user/package")`
        -   clone the repository and install from local copy
